/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Service health (no auth) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Health"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models, runner and policy details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SystemInfo"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the first admin account (only while no user exists)
         * @description From the device itself no code is needed. From another machine the body must carry
         *     `setup_code` (the one-time code the installer generated in `/etc/guard/guard.env`);
         *     wrong codes are throttled. An optional `community` object saves the community profile
         *     in the same call.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SetupRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResult"];
                    };
                };
                403: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Community profile (public, so the login screen can show it) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Community"];
                    };
                };
            };
        };
        /** Update the community profile (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CommunityInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Community"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/logo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Community logo image (public) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PNG */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": string;
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Replace the logo (admin; multipart field `logo`, PNG/JPEG/WebP, max 2 MB) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        logo: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Community"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Remove the logo (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Community"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Credentials"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResult"];
                    };
                };
                401: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the current session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Logged out */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change your own password */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        current_password: string;
                        new_password: string;
                    };
                };
            };
            responses: {
                /** @description Changed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All users (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["UserList"];
                    };
                };
            };
        };
        put?: never;
        /** Create a user (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Update a user (admin); give `password` to reset it. Disabling or resetting signs the user out. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UserInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["User"];
                    };
                };
                /** @description Would leave no active administrator */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a user (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                409: components["responses"]["Error"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin dashboard (admin) - camera visits only; buckets in the device's local time */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dashboard"];
                    };
                };
                403: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List drivers */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DriverList"];
                    };
                };
            };
        };
        put?: never;
        /** Create a driver (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DriverInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get a driver */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Update a driver (admin; omitted fields are kept) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DriverInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a driver (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{id}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll face photos (admin). Each photo's most prominent face becomes a template. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        photos?: string[];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["EnrollResult"];
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        /** Remove all face templates (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{id}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Profile picture image (admin-only for now, unlike the community logo) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PNG */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/*": string;
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Set the profile picture (admin; multipart field `photo`, PNG/JPEG/WebP, max 2 MB) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        photo: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        post?: never;
        /** Remove the profile picture (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/{id}/vehicles/{vehicleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
                vehicleId: number;
            };
            cookie?: never;
        };
        get?: never;
        /** Authorize the driver for the vehicle (admin) */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    vehicleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
            };
        };
        post?: never;
        /** Remove the authorization (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                    vehicleId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List vehicles */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VehicleList"];
                    };
                };
            };
        };
        put?: never;
        /** Register a vehicle together with its owner (admin). Owner is required and created atomically. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
                /** @description Missing/invalid owner */
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Get a vehicle */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
            };
        };
        /** Update a vehicle (admin; omitted fields are kept). Does not change the owner. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["VehicleInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
            };
        };
        post?: never;
        /** Delete a vehicle (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/vehicles/{id}/owner": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        /** Set the owner on a vehicle that doesn't have one yet (admin). For backfilling vehicles created before this feature existed. */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OwnerInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Vehicle"];
                    };
                };
                /** @description Vehicle already has an owner */
                409: components["responses"]["Error"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/drivers/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem an owner's authorization code to add a new authorized (non-owner) driver to their vehicle (admin) — the owner doesn't need to be present. Wrong-code attempts are rate-limited (5 per 5 minutes), same as the first-run setup code. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["DriverInput"] & {
                        /** @description e.g. XXXX-XXXX */
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Driver"];
                    };
                };
                /** @description Code not recognized */
                400: components["responses"]["Error"];
                /** @description Too many wrong codes */
                403: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List analysis jobs, newest first */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobList"];
                    };
                };
            };
        };
        put?: never;
        /** Upload a video for analysis */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        video: string;
                    };
                };
            };
            responses: {
                /** @description Queued */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                413: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Get a job (includes the result once completed) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a finished job and its media (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued or running job */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Cancelling */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/video": {
        parameters: {
            query?: {
                /** @description Alternative to the Authorization header */
                access_token?: components["parameters"]["AccessToken"];
            };
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** The uploaded video (supports Range requests) */
        get: {
            parameters: {
                query?: {
                    /** @description Alternative to the Authorization header */
                    access_token?: components["parameters"]["AccessToken"];
                };
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Video bytes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{jobId}/frames": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: components["parameters"]["JobId"];
            };
            cookie?: never;
        };
        /** Per-frame detections of a completed job (for overlays) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    jobId: components["parameters"]["JobId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FramesDocument"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cameras with their live status */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CameraList"];
                    };
                };
            };
        };
        put?: never;
        /** Add a camera (admin); enabled cameras start immediately */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CameraInput"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Camera"];
                    };
                };
                400: components["responses"]["Error"];
                409: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Try a camera source without saving it (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        source: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProbeResult"];
                    };
                };
                400: components["responses"]["Error"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** One camera */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Camera"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        /** Update a camera (admin); fields not given are kept */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CameraInput"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Camera"];
                    };
                };
            };
        };
        post?: never;
        /** Remove a camera (admin); its access events are kept */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/live.mjpeg": {
        parameters: {
            query?: {
                /** @description Alternative to the Authorization header */
                access_token?: components["parameters"]["AccessToken"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Live view as MJPEG (use as <img src>), about 10 fps */
        get: {
            parameters: {
                query?: {
                    /** @description Alternative to the Authorization header */
                    access_token?: components["parameters"]["AccessToken"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description multipart/x-mixed-replace stream of JPEG frames */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cameras/{id}/preview.jpg": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** The current frame as one JPEG */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JPEG image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": unknown;
                    };
                };
                503: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Access log, newest first */
        get: {
            parameters: {
                query?: {
                    limit?: components["parameters"]["Limit"];
                    offset?: components["parameters"]["Offset"];
                    camera_id?: number;
                    source?: "camera" | "video";
                    verdict?: components["schemas"]["Verdict"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessEventList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-events/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** One access event */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AccessEvent"];
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access-events/{id}/snapshot.jpg": {
        parameters: {
            query?: {
                /** @description Alternative to the Authorization header */
                access_token?: components["parameters"]["AccessToken"];
            };
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        /** Snapshot of a camera visit (boxes are in details.overlay) */
        get: {
            parameters: {
                query?: {
                    /** @description Alternative to the Authorization header */
                    access_token?: components["parameters"]["AccessToken"];
                };
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description JPEG image */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/jpeg": unknown;
                    };
                };
                404: components["responses"]["Error"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Alerts, newest first */
        get: {
            parameters: {
                query?: {
                    /** @description Only unresolved alerts */
                    open?: "true" | "false";
                    limit?: components["parameters"]["Limit"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AlertList"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge an alert */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts/{id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["Id"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve an alert */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["Id"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alert"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live event stream (Server-Sent Events) */
        get: {
            parameters: {
                query?: {
                    /** @description Only this job's events (replays buffered ones) */
                    job?: string;
                    /** @description Only this camera's live events */
                    camera?: number;
                    /** @description Alternative to the Authorization header */
                    access_token?: components["parameters"]["AccessToken"];
                };
                header?: {
                    "Last-Event-ID"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description text/event-stream of Event envelopes */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": components["schemas"]["Event"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description validation_error | unauthorized | forbidden | not_found | conflict | too_large | unavailable | internal_error */
            error: string;
            message: string;
        };
        /** @enum {string} */
        Status: "active" | "inactive" | "blacklisted";
        SetupRequest: {
            username: string;
            password: string;
            /** @description Required when not called from the device itself */
            setup_code?: string;
            community?: components["schemas"]["CommunityInput"];
        };
        CommunityInput: {
            name?: string;
            address?: string;
            city?: string;
            country?: string;
            helpline?: string;
            email?: string;
            website?: string;
        };
        Community: {
            /** @description true once the community has a name */
            configured: boolean;
            name: string;
            address: string;
            city: string;
            country: string;
            helpline: string;
            email: string;
            website: string;
            /** @description Server-relative URL of the logo */
            logo_url: string | null;
        };
        Health: {
            /** @enum {string} */
            status: "ok" | "degraded";
            version: string;
            uptime_s: number;
            setup_required: boolean;
            inference: {
                /** @enum {string} */
                status: "offline" | "loading" | "ok" | "error";
                message: string;
            };
            disk: {
                /** Format: int64 */
                free_bytes: number;
                /** Format: int64 */
                total_bytes: number;
            };
        };
        SystemInfo: {
            version: string;
            models?: {
                [key: string]: unknown;
            } | null;
            runner: {
                current_job?: string | null;
            };
            policy: {
                match_threshold: number;
                min_face_frames: number;
                min_plate_reads: number;
                sample_fps: number;
            };
            live?: {
                visit_gap_s?: number;
                max_visit_s?: number;
                repeat_suppress_s?: number;
                snapshot_retention_days?: number;
                cameras?: number;
            };
        };
        CameraInput: {
            name?: string;
            /**
             * @description csi://0[?width=&height=&fps=] (Jetson CSI), usb://0 or /dev/video0 (USB),
             *     rtsp://user:pass@host/path (IP camera), http(s)://... (MJPEG/HLS),
             *     file:///path/clip.mp4 (looped, for testing), gst://<pipeline ending in appsink>
             */
            source?: string;
            /** @default true */
            enabled: boolean;
            /** @description Frames analysed per second */
            sample_fps?: number;
        };
        CameraStatus: {
            /** @enum {string} */
            state: "starting" | "waiting" | "connecting" | "live" | "reconnecting" | "error" | "disabled";
            message: string;
            analysis_fps: number;
            width: number;
            height: number;
            /** Format: date-time */
            last_frame_at: string | null;
            /** @description Something is in view right now */
            visit_active: boolean;
        };
        Camera: {
            /** Format: int64 */
            id: number;
            name: string;
            source: string;
            enabled: boolean;
            sample_fps: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            status: components["schemas"]["CameraStatus"];
        };
        CameraList: {
            items: components["schemas"]["Camera"][];
        };
        ProbeResult: {
            ok: boolean;
            error?: string;
            backend?: string;
            width?: number;
            height?: number;
            fps?: number;
        };
        /** @description data of a camera.frame event */
        LiveFrame: {
            /** Format: int64 */
            camera_id: number;
            frame: number;
            /**
             * Format: int64
             * @description Capture time
             */
            ts: number;
            width: number;
            height: number;
            faces: components["schemas"]["FaceDetection"][];
            plates: components["schemas"]["PlateDetection"][];
            visit_active: boolean;
        };
        Overlay: {
            width: number;
            height: number;
            faces: components["schemas"]["FaceDetection"][];
            plates: components["schemas"]["PlateDetection"][];
        };
        VerdictCounts: {
            /** @description YYYY-MM-DD HH:00 (hourly) or YYYY-MM-DD (daily), local time */
            bucket: string;
            total: number;
            authorized: number;
            unauthorized: number;
            unknown_driver: number;
            unknown_vehicle: number;
            unknown_both: number;
        };
        Dashboard: {
            today: components["schemas"]["VerdictCounts"];
            yesterday: components["schemas"]["VerdictCounts"];
            /** @description Last 24 hours */
            hourly: components["schemas"]["VerdictCounts"][];
            /** @description Last 14 days */
            daily: components["schemas"]["VerdictCounts"][];
            cameras: (components["schemas"]["Camera"] & {
                visits_today: number;
            })[];
            cameras_enabled: number;
            cameras_live: number;
            unregistered_plates: {
                plate: string;
                count: number;
                /** Format: date-time */
                last_seen: string;
                camera: string | null;
            }[];
            top_drivers: {
                /** Format: int64 */
                driver_id: number;
                name: string;
                visits: number;
                authorized: number;
            }[];
            alerts: {
                open: number;
                open_critical: number;
                unacknowledged: number;
                /** @description Median time to acknowledge (people only) */
                median_response_s: number | null;
                responses_7d: number;
                recent_open: components["schemas"]["Alert"][];
            };
            system: {
                version: string;
                uptime_s: number;
                inference: {
                    status: string;
                    message: string;
                };
                /** Format: int64 */
                disk_free_bytes: number;
                /** Format: int64 */
                disk_total_bytes: number;
                /** Format: int64 */
                snapshot_bytes: number;
                /** Format: int64 */
                database_bytes: number;
                snapshot_retention_days: number;
                active_admins: number;
                active_guards: number;
            };
        };
        Credentials: {
            username: string;
            password: string;
        };
        /** @enum {string} */
        Role: "admin" | "guard";
        User: {
            /** Format: int64 */
            id: number;
            username: string;
            full_name: string;
            role: components["schemas"]["Role"];
            active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at: string | null;
        };
        UserInput: {
            /** @description 3-32 characters; set on creation only */
            username?: string;
            full_name?: string;
            /** @description Required on creation; on update resets it */
            password?: string;
            role?: components["schemas"]["Role"];
            active?: boolean;
        };
        UserList: {
            items: components["schemas"]["User"][];
        };
        LoginResult: {
            token: string;
            user: components["schemas"]["User"];
            expires_in_hours: number;
        };
        DriverInput: {
            name?: string;
            status?: components["schemas"]["Status"];
            phone?: string;
            notes?: string;
        };
        OwnerInput: {
            name: string;
            /** @description Mandatory: mobile/WhatsApp number, 7-15 digits */
            phone: string;
            notes?: string;
        };
        Driver: {
            /** Format: int64 */
            id: number;
            name: string;
            status: components["schemas"]["Status"];
            phone: string;
            notes: string;
            /** @description Auto-enrolled owner of a vehicle; set once, at creation */
            is_owner: boolean;
            photo_count: number;
            /** @description Admin-only (omitted entirely for guards): profile picture, set via PUT /drivers/{id}/photo */
            photo_url?: string | null;
            vehicles: {
                /** Format: int64 */
                id: number;
                plate_number: string;
            }[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DriverList: {
            items: components["schemas"]["Driver"][];
        };
        EnrollResult: {
            enrolled: number;
            photos: {
                filename: string;
                enrolled: boolean;
                /** @description no_face | invalid_image */
                error: string | null;
            }[];
            driver: components["schemas"]["Driver"];
        };
        VehicleInput: {
            plate_number?: string;
            make?: string;
            model?: string;
            color?: string;
            status?: components["schemas"]["Status"];
            /** @description Required when creating a new vehicle (not used on update): the owner is created as a driver, auto-enrolled and authorized for this vehicle, in the same atomic request. Ignored by PUT /vehicles/{id} — see PUT /vehicles/{id}/owner to set an owner on a vehicle that doesn't have one yet. */
            owner?: components["schemas"]["OwnerInput"];
        };
        Vehicle: {
            /** Format: int64 */
            id: number;
            plate_number: string;
            /** @description Uppercase A-Z/0-9 form used for matching */
            plate_normalized: string;
            make: string;
            model: string;
            color: string;
            status: components["schemas"]["Status"];
            drivers: {
                /** Format: int64 */
                id: number;
                name: string;
            }[];
            /** @description null only for a vehicle created before this feature existed and not yet backfilled */
            owner: {
                /** Format: int64 */
                id: number;
                name: string;
                phone: string;
            } | null;
            /** @description Admin-only (omitted entirely for guards): the owner's reusable code, redeemed via POST /drivers/authorize */
            auth_code?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        VehicleList: {
            items: components["schemas"]["Vehicle"][];
        };
        /** @enum {string} */
        Verdict: "authorized" | "unauthorized" | "unknown_driver" | "unknown_vehicle" | "unknown_both";
        VideoInfo: {
            width?: number;
            height?: number;
            fps?: number;
            total_frames?: number;
        };
        JobResult: {
            verdict: components["schemas"]["Verdict"];
            authorized: boolean;
            blacklisted: boolean;
            reason: string;
            driver: {
                /** Format: int64 */
                id: number;
                name: string;
                similarity: number;
                frames: number;
            } | null;
            vehicle: {
                /** Format: int64 */
                id: number;
                plate_number: string;
                reads: number;
            } | null;
            drivers_seen: {
                /** Format: int64 */
                id: number;
                name: string;
                status: string;
                frames: number;
                best_similarity: number;
            }[];
            plates_read: {
                text: string;
                reads: number;
                /** Format: int64 */
                vehicle_id: number | null;
            }[];
            faces_seen: number;
            unknown_faces: number;
            frames_analysed: number;
            video?: components["schemas"]["VideoInfo"];
            processing_ms?: number;
        };
        Job: {
            id: string;
            /** @enum {string} */
            status: "queued" | "running" | "completed" | "failed" | "cancelled";
            original_name: string;
            /** Format: int64 */
            size_bytes: number;
            attempts: number;
            /** @description 0..1 */
            progress: number;
            verdict: components["schemas"]["Verdict"] | null;
            result: components["schemas"]["JobResult"] | null;
            error: string | null;
            created_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            started_at: string | null;
            /** Format: date-time */
            finished_at: string | null;
            /** @description Jobs ahead of this one (queued jobs only) */
            queue_position?: number;
        };
        JobList: {
            items: components["schemas"]["Job"][];
        };
        /** @description [x, y, width, height] in video pixels */
        BBox: number[];
        FaceDetection: {
            bbox: components["schemas"]["BBox"];
            conf: number;
            /** Format: int64 */
            driver_id?: number;
            driver_name?: string;
            similarity?: number;
        };
        PlateDetection: {
            bbox: components["schemas"]["BBox"];
            conf: number;
            /** @description Normalized OCR text */
            text: string;
            text_conf: number;
            /** Format: int64 */
            vehicle_id?: number;
        };
        Frame: {
            frame: number;
            t_ms: number;
            faces: components["schemas"]["FaceDetection"][];
            plates: components["schemas"]["PlateDetection"][];
        };
        FramesDocument: {
            video: components["schemas"]["VideoInfo"];
            frames: components["schemas"]["Frame"][];
        };
        AccessEvent: {
            /** Format: int64 */
            id: number;
            /**
             * Format: date-time
             * @description Start of the visit (camera) or analysis time (video)
             */
            event_time: string;
            /** Format: date-time */
            ended_at: string | null;
            /** @enum {string} */
            source: "camera" | "video";
            job_id: string | null;
            /** Format: int64 */
            camera_id: number | null;
            camera_name: string | null;
            has_snapshot: boolean;
            verdict: components["schemas"]["Verdict"];
            authorized: boolean;
            /** Format: int64 */
            driver_id: number | null;
            driver_name: string | null;
            /** Format: int64 */
            vehicle_id: number | null;
            plate_text: string;
            details: {
                reason?: string;
                frames?: number;
                duration_ms?: number;
                overlay?: components["schemas"]["Overlay"];
            };
        };
        AccessEventList: {
            items: components["schemas"]["AccessEvent"][];
        };
        Alert: {
            /** Format: int64 */
            id: number;
            /** Format: date-time */
            created_at: string;
            /** @enum {string} */
            severity: "info" | "warning" | "critical";
            /** @enum {string} */
            kind: "unauthorized" | "blacklisted" | "unknown_driver" | "camera_offline" | "system";
            message: string;
            /** Format: int64 */
            access_event_id: number | null;
            /** Format: date-time */
            acknowledged_at: string | null;
            /** Format: date-time */
            resolved_at: string | null;
            /** @description Username */
            acknowledged_by: string | null;
            resolved_by: string | null;
        };
        AlertList: {
            items: components["schemas"]["Alert"][];
        };
        /**
         * @description SSE envelope. `data` depends on `type`:
         *     job.queued / job.cancelled / job.failed / job.completed → Job;
         *     job.started → {job: Job, video: VideoInfo};
         *     job.frame → Frame + {job_id, progress};
         *     camera.frame → LiveFrame (high rate, not replayed after long gaps);
         *     camera.status → {camera_id, state, message};
         *     access.event → AccessEvent (a camera visit or test video was decided);
         *     alert.created / alert.updated → Alert.
         */
        Event: {
            /** @enum {string} */
            type: "job.queued" | "job.started" | "job.frame" | "job.completed" | "job.failed" | "job.cancelled" | "camera.frame" | "camera.status" | "access.event" | "alert.created" | "alert.updated";
            data: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        Id: number;
        JobId: string;
        Limit: number;
        Offset: number;
        /** @description Alternative to the Authorization header */
        AccessToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
